name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.vscode/**'
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - steam_legacy
          - public
        mod:
        #   - valve
          - cstrike
        #   - czero
        #   - dod
        #   - gearbox
        #   - tfc
        #   - ricochet
        #   - dmc

    env:
      needToPush: ${{ github.ref == 'refs/heads/master' }}

    steps:
    - uses: actions/checkout@v4.2.0
    - uses: docker/setup-buildx-action@v3.7.0

    - name: Log in to Docker Hub
      if: ${{ env.needToPush }}
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PERSONAL_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.7.0
      env:
        OWNER: ${{ vars.DOCKER_USERNAME }}
        REPO: ${{ vars.DOCKER_REPOSITORY }}
        TAG: ${{ matrix.branch }}
      with:
        context: .
        file: ./Dockerfile
        push: ${{ env.needToPush }}
        tags: |
          ${{ env.OWNER }}/${{ env.REPO }}:${{ env.TAG }}
          ${{ env.TAG == 'steam_legacy' && format('{0}/{1}:latest', env.OWNER, env.REPO) || null}}
        build-args: |
          APPBRANCH=${{ matrix.branch }}
          MOD=${{ matrix.mod }}
        cache-from: type=gha,scope=build-${{ matrix.mod }}-${{ matrix.branch }}
        cache-to: type=gha,mode=max,scope=build-${{ matrix.mod }}-${{ matrix.branch }}